# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd01090c4001d23c57cf2ce948eb680b6699ca4cd8249e48443f94b98ee4f17074ac1b51dadf8f1782f10cbdffec548ef07b4d2a95c1a3785284b651d0535511

test:
  secret_key_base: 8f4da36d113cec57e4e1742c53db03d735e6933416337db754d6bd0e7ce4c5747dcb45286d0bae3f9dbfe17151d466a8cdf84a0ac886e4fcae7d2046a16c8c84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
